[tool.poetry] 
name = "rt"
version = "0.1.0"
description = ""
authors = ["Hampus Fröjdholm <hampus.frojdholm@gmail.com>"]
readme = "README.md"
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.group.dev.dependencies]
python-lsp-server = {extras = ["all"], version = "^1.9.0"}

[tool.poetry.scripts]
rt-server = "rt.server:main"
rt-example-engine = "rt.engine:run"
rt-arena = "rt.arena:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
